spring:
  datasource:
    url: jdbc:mariadb://${db_url}/escape_manager?autoReconnect=true&rewriteBatchedStatements=true
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        show_sql: false
        default_batch_fetch_size: 100
        format_sql: false

security:
  jwt:
    expiry: 604800